Add command line migration
MichaelBelgium/mybb_to_flarum pull request #23
Opened 2020-11-19 05:31 UTC by Javier-Rotelli

since most of the flarum installations have access to the console, added an option to run the migration from it.

It may need some revisions to the options and its default values, but right now it's functional.

2020-11-20 15:49 UTC, MichaelBelgium commented
Could you add some information/explanation about the command in the readme?

2020-11-20 21:32 UTC, Javier-Rotelli commented
hey, sure. I didn't add it because I wanted to be sure yopu were alright with this approach

2020-11-21 11:40 UTC, MichaelBelgium commented
I didn't test it yet but having a command is a nice addition, although i'm not sure if it's easier with all these options than in the browser.

2020-11-23 04:10 UTC, Javier-Rotelli commented
Added the command line to the Readme. let me know if it isn't enough. 
yeah, it's not easier at first, but if anything happens (and in my experience something always happens 😬 ) the feedback is easier to follow, and once you wrote the command you don't need to write it again.

2021-02-02 22:39 UTC, MichaelBelgium requested changes
Sorry for the late check/review but if these changes are resolved you'll get a merge 😛

2021-02-02 22:39 UTC, MichaelBelgium commented on src/Commands/MybbToFlarumCommand.php
> +        'password'=> ['password', 'p', InputOption::VALUE_OPTIONAL, 'password for the mybb database', false],
Is `false` the default value? Would be better if it's an empty string

2021-02-02 22:39 UTC, MichaelBelgium commented on src/Commands/MybbToFlarumCommand.php
> +            );
Can you make sure that the options "host", "user" and "db" are always required and no empty strings? There is InputOption::VALUE_REQUIRED but if you do the interactive mode it's not checking if it's filled in somehow ...

2021-02-02 22:39 UTC, MichaelBelgium commented on src/Commands/MybbToFlarumCommand.php
> +}
Not really a fan of calling this function every time after it migrated something.

Could u change it so it'd look like, for example:

```
$this->info("2 user groups migrated");
$this->info("15 discussions migrated")
...;
```

Also with the use of `$migrator->getProcessedCount()` ofcourse

2021-02-10 16:47 UTC, Javier-Rotelli commented
hey! better late than never!. I'll address your comments during the weekend

2021-05-07 00:42 UTC, Javier-Rotelli commented on src/Commands/MybbToFlarumCommand.php
> +        'password'=> ['password', 'p', InputOption::VALUE_OPTIONAL, 'password for the mybb database', false],
done

2021-05-07 00:42 UTC, Javier-Rotelli commented on src/Commands/MybbToFlarumCommand.php
> +            );
done

2021-05-07 00:42 UTC, Javier-Rotelli commented on src/Commands/MybbToFlarumCommand.php
> +}
I'm not 100% sure I got you here. but take a look at the new version and let me know what you think

2021-05-07 01:01 UTC, Javier-Rotelli commented
well, took me long enough to get to the weekend 😬  hope this is ok.

2021-05-07 11:57 UTC, MichaelBelgium commented on src/Commands/MybbToFlarumCommand.php
> +}
Yeah almost, I only wanted to have "x user groups migrated" and not 

> user groups migrated

> x user groups migrated

one time is fine with the count

2021-05-07 12:18 UTC, MichaelBelgium approved these changes

2021-05-07 12:19 UTC, merged